# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-30 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180528_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='wwatchers',
        ),
        migrations.AddField(
            model_name='component',
            name='author',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='component',
            name='author_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='component',
            name='homepage_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='component',
            name='license',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='component',
            name='npm_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='component',
            name='watchers',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='commits',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='created_time',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='downloads',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='forks',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='no_of_contributors',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='stars',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='tags',
            field=models.ManyToManyField(null=True, to='main.Tag'),
        ),
    ]
