# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-03 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180530_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='modified_time',
            field=models.DateTimeField(null=True),
        ),
    ]
