# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-03 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20180603_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='author',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
