# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-09 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20180603_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='created_time',
            field=models.DateTimeField(null=True),
        ),
    ]
