# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-20 22:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20180616_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSSDependency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('css_url', models.URLField(null=True)),
                ('component', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Component')),
            ],
        ),
        migrations.CreateModel(
            name='JSDependency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('js_url', models.URLField(null=True)),
                ('component', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Component')),
            ],
        ),
        migrations.CreateModel(
            name='Visualization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.URLField(null=True)),
                ('component', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Component')),
            ],
        ),
    ]
