# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-24 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_cssdependency_jsdependency_visualization'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='github_update_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='component',
            name='latest_commit_hash',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
