# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-26 06:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_sniperdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('name', models.CharField(max_length=50)),
                ('sniperData', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.SniperData')),
            ],
        ),
    ]
