# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-26 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='sniperdata',
            name='snippets_dir_name',
            field=models.CharField(default='snippets', max_length=50),
        ),
    ]
