# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-13 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_sniperdata_snippets_dir_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cssdependency',
            name='sniper_data_value',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jsdependency',
            name='sniper_data_value',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
