# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-02 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20180713_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='license',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='version',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cssdependency',
            name='sniper_data_value',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jsdependency',
            name='sniper_data_value',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sniperdata',
            name='snippets_dir_name',
            field=models.CharField(default='snippets', max_length=100),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='visualization',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
