# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-02 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20180802_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cssdependency',
            name='sniper_data_value',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='jsdependency',
            name='sniper_data_value',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
