# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-15 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20180802_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='tags',
            field=models.ManyToManyField(to='main.Tag'),
        ),
    ]
